import { ICaracteristicaClienteFornecedorDTO } from "./ICaracteristicaClienteFornecedorDTO";
import { IDadosBancariosDTO } from "./IDadosBancariosDTO";
import { IEnderecoEntregaDTO } from "./IEnderecoEntregaDTO";
import { IInfoDTO } from "./IInfoDTO";
import { IRecomendacaoDTO } from "./IRecomendacaoDTO";
import { ITagDTO } from "./ITagDTO";

interface IClienteFornecedorDTO {
  codigo_cliente_omie?: number;
  codigo_cliente_integracao?: string;
  razao_social?: string;
  cnpj_cpf?: string;
  nome_fantasia?: string;
  telefone1_ddd?: string;
  telefone1_numero?: string;
  contato?: string;
  endereco?: string;
  endereco_numero?: string;
  bairro?: string;
  complemento?: string;
  estado?: string;
  cidade?: string;
  cep?: string;
  codigo_pais?: string;
  separar_endereco?: string;
  telefone2_ddd?: string;
  telefone2_numero?: string;
  recomendacoes?: IRecomendacaoDTO;
  enderecoEntrega?: IEnderecoEntregaDTO;
  dadosBancarios?: IDadosBancariosDTO;
  info?: IInfoDTO;
  fax_ddd?: string;
  fax_numero?: string;
  email?: string;
  homepage?: string;
  inscricao_estadual?: string;
  inscricao_municipal?: string;
  inscricao_suframa?: string;
  optante_simples_nacional?: string;
  tipo_atividade?: string;
  cnae?: string;
  produtor_rural?: string;
  contribuinte?: string;
  observacao?: string;
  obs_detalhadas?: string;
  recomendacao_atraso?: string;
  pessoa_fisica?: string;
  exterior?: string;
  logradouro?: string;
  importado_api?: string;
  bloqueado?: string;
  cidade_ibge?: string;
  valor_limite_credito?: number;
  bloquear_faturamento?: string;
  recomendacoes_numero_parcelas?: string;
  recomendacoes_codigo_vendedor?: number;
  recomnedacoes_email_fatura?: string;
  recomendacoes_gerar_boletos?: string;
  recomendacoes_codigo_transportadora?: number;
  enderentrega_entRazaoSocial?: string;
  enderentrega_entCnpjCpf?: string;
  enderentrega_entEndereco?: string;
  enderentrega_entNumero?: string;
  enderentrega_entComplemento?: string;
  enderentrega_entBairro?: string;
  enderentrega_entCEP?: string;
  enderentrega_entEstado?: string;
  enderentrega_entCidade?: string;
  enderentrega_entSepararEndereco?: string;
  enderentrega_entTelefone?: string;
  enderentrega_entIE?: string;
  nif?: string;
  documento_exterior?: string;
  inativo?: string;
  dadosBancarios_codigo_banco?: string;
  dadosBancarios_agencia?: string;
  dadosBancarios_conta_corrente?: string;
  dadosBancarios_doc_titular?: string;
  dadosBancarios_nome_titular?: string;
  info_data_inclusao?: string;
  info_usuario_inclusao?: string;
  info_data_alteracao?: string;
  info_usuario_alteracao?: string;
  info_importado_api?: string;
  bloquear_exclusao?: string;
  ID_Empresa?: number;
  tags?: ITagDTO[];
  caracteristicas?: ICaracteristicaClienteFornecedorDTO[];
  setCreateDate(): void;
  setUpdateDate(): void;
}

export { IClienteFornecedorDTO };
