import { IBoletoDTO } from "./IBoletoDTO";
import { ICategoriaContaReceberDTO } from "./ICategoriaContaReceberDTO";
import { IDistriuicaoContaReceberDTO } from "./IDistribuicaoContaReceberDTO";
import { IInfoDTO } from "./IInfoDTO";
import { ILancamentoDetalheDTO } from "./ILancamentoDetalheDTO";

interface IContaReceberDTO {
  ID_Empresa?: number;
  info?: IInfoDTO;
  chave_lancamento?: number;
  codigo_lancamento_omie?: number;
  codigo_lancamento_integracao?: string;
  codigo_cliente_fornecedor?: number;
  codigo_cliente_fornecedor_integracao?: string;
  data_vencimento?: string;
  valor_documento?: number;
  codigo_categoria?: string;
  data_previsao?: string;
  categorias?: ICategoriaContaReceberDTO[];
  id_conta_corrente?: number;
  numero_documento?: string;
  numero_parcela?: string;
  codigo_tipo_documento?: string;
  numero_documento_fiscal?: string;
  numero_pedido?: string;
  chave_nfe?: string;
  observacao?: string;
  codigo_barras_ficha_compensacao?: string;
  codigo_cmc7_cheque?: string;
  data_emissao?: string;
  id_origem?: string;
  operacao?: string;
  valor_pis?: number;
  retem_pis?: string;
  valor_cofins?: number;
  retem_cofins?: string;
  valor_csll?: number;
  retem_csll?: string;
  valor_ir?: number;
  retem_ir?: string;
  valor_iss?: number;
  retem_iss?: string;
  valor_inss?: number;
  retem_inss?: string;
  bloqueado?: string;
  bloquear_baixa?: string;
  importado_api?: string;
  baixar_documento?: string;
  conciliar_documento?: string;
  acao?: string;
  lancamento_detalhe?: ILancamentoDetalheDTO[];
  distribuicao?: IDistriuicaoContaReceberDTO[];
  status_titulo?: string;
  codigo_vendedor?: number;
  codigo_projeto?: number;
  nsu?: string;
  data_registro?: string;
  tipo_agrupamento?: string;
  info_data_inclusao?: string;
  info_usuario_inclusao?: string;
  info_data_alteracao?: string;
  info_usuario_alteracao?: string;
  info_importado_api?: string;
  boleto?: IBoletoDTO;
  nCodPedido?: number;
  bloquear_exclusao?: string;
  nCodOS?: number;
  cGerado?: string;
  dDtEmBol?: string;
  cNumBoleto?: string;
  cNumBancario?: string;
  nPerJuros?: number;
  nPerMulta?: number;
  cCodDep?: string;
  codigos_departamentos?: IDistriuicaoContaReceberDTO[];
}

export { IContaReceberDTO };
