import { IDetalhesMovimentoFinanceiroDTO } from "./IDetalhesMovimentoFinanceiroDTO";
import { IMovimentoFinanceiroCategoriaDTO } from "./IMovimentoFinanceiroCategoriaDTO";
import { IMovimentoFinanceiroDepartamentoDTO } from "./IMovimentoFinanceiroDepartamentoDTO";
import { IResumoMovimentoFinanceiroDTO } from "./IResumoMovimentoFinanceiroDTO";

interface IMovimentoFinanceiroDTO {
  detalhes?: IDetalhesMovimentoFinanceiroDTO;
  resumo?: IResumoMovimentoFinanceiroDTO;
  departamentos?: IMovimentoFinanceiroDepartamentoDTO[];
  categorias?: IMovimentoFinanceiroCategoriaDTO[];
  nCodTitulo?: number;
  cCodIntTitulo?: string;
  cNumTitulo?: string;
  dDtEmissao?: string;
  dDtVenc?: string;
  dDtPrevisao?: string;
  dDtPagamento?: string;
  nCodCliente?: number;
  cCPFCNPJCliente?: string;
  nCodCtr?: number;
  cNumCtr?: string;
  nCodOS?: number;
  cNumOS?: string;
  nCodCC?: number;
  cStatus?: string;
  cNatureza?: string;
  cTipo?: string;
  cOperacao?: string;
  cNumDocFiscal?: string;
  cCodCateg?: string;
  cNumParcela?: string;
  nValorTitulo?: number;
  nValorPIS?: number;
  cRetPIS?: string;
  nValorCOFINS?: number;
  cRetCOFINS?: string;
  nValorCSLL?: number;
  cRetCSLL?: string;
  nValorIR?: number;
  cRetIR?: string;
  nValorISS?: number;
  cRetISS?: string;
  nValorINSS?: number;
  cRetINSS?: string;
  cCodProjeto?: number;
  observacao?: string;
  cCodVendedor?: number;
  nCodComprador?: number;
  cCodigoBarras?: string;
  cNSU?: string;
  nCodNF?: number;
  dDtRegistro?: string;
  cNumBoleto?: string;
  cChaveNFe?: string;
  cOrigem?: string;
  nCodTitRepet?: number;
  cGrupo?: string;
  nCodMovCC?: number;
  nValorMovCC?: number;
  nCodMovCCRepet?: number;
  nDesconto?: number;
  nJuros?: number;
  nMulta?: number;
  nCodBaixa?: number;
  dDtCredito?: string;
  dDtConcilia?: string;
  cUsConcilia?: string;
  dDtInc?: string;
  cUsInc?: string;
  dDtAlt?: string;
  cUstAlt?: string;
  resumo_cLiquidado?: string;
  resumo_nValPago?: number;
  resumo_nValAberto?: number;
  resumo_nDesconto?: number;
  resumo_nJuros?: number;
  resumo_nMulta?: string;
  resumo_nValLiquido?: string;
  ID_Empresa?: number;
  setCreateDate(): void;
  setUpdateDate(): void;
}

export { IMovimentoFinanceiroDTO };
