import { ICaracteristicaProdutoDTO } from "./ICaracteristicaProdutoDTO";
import { IDadosIbptDTO } from "./IDadosIbptDTO";
import { IImagenProdutoDTO } from "./IImagemProdutoDTO";
import { IInfoDTO } from "./IInfoDTO";
import { IKitProdutoDTO } from "./IKitProdutoDTO";
import { IRecomendacoesFiscaisDTO } from "./IRecomendacoesFiscaisDTO";
import { IVideoProdutoDTO } from "./IVideoProdutoDTO";

interface IProdutoDTO {
  codigo_produto?: number;
  ID_Empresa?: number;
  imagens: IImagenProdutoDTO[];
  videos: IVideoProdutoDTO[];
  caracteristicas: ICaracteristicaProdutoDTO[];
  componentes_kit: IKitProdutoDTO[];
  info: IInfoDTO;
  dadosIbpt: IDadosIbptDTO;
  recomendacoes_fiscais: IRecomendacoesFiscaisDTO;
  codigo_produto_integracao?: string;
  descricao?: string;
  codigo?: string;
  unidade?: string;
  ncm?: string;
  ean?: string;
  valor_unitario?: number;
  codigo_familia?: number;
  tipoItem?: string;
  origem_mercadoria?: string;
  id_preco_tabelado?: number;
  id_cest?: string;
  cupom_fiscal?: string;
  market_place?: string;
  indicador_escala?: string;
  cnpj_fabricante?: string;
  peso_liq?: number;
  peso_bruto?: number;
  altura?: number;
  largura?: number;
  profundidade?: number;
  marca?: string;
  modelo?: string;
  dias_garantia?: number;
  dias_crossdocking?: number;
  descr_detalhada?: string;
  obs_internas?: string;
  info_dInc?: string;
  info_uInc?: string;
  info_dAlt?: string;
  info_uAlt?: string;
  cImpAPI?: string;
  exibir_descricao_nfe?: string;
  exibir_descricao_pedido?: string;
  cst_icms?: string;
  modalidade_icms?: string;
  csosn_icms?: string;
  aliquota_icms?: number;
  red_base_icms?: number;
  motivo_deson_icms?: string;
  per_icms_fcp?: number;
  codigo_beneficio?: string;
  cst_pis?: string;
  aliquota_pis?: number;
  cst_cofins?: string;
  aliquota_cofins?: number;
  cfop?: string;
  dadosIbpt_aliqFederal?: number;
  dadosIbpt_aliqEstadual?: number;
  dadosIbpt_aliqMunicipal?: number;
  dadosIbpt_fonte?: string;
  dadosIbpt_chave?: string;
  dadosIbpt_versao?: string;
  dadosIbpt_valido_de?: string;
  dadosIbpt_valido_ate?: string;
  codInt_familia?: string;
  descricao_familia?: string;
  bloqueado?: string;
  bloquear_exclusao?: string;
  importado_api?: string;
  inativo?: string;
  lead_time?: number;
  aliquota_ibpt?: number;
  cest?: string;
  quantidade_estoque?: number;
  estoque_minimo?: number;
  setCreateDate(): void;
  setUpdateDate(): void;
}

export { IProdutoDTO };
